### ISSUE TITLE
World problem

### ISSUE THREAD

**Issue by jimmyl0l3c** [Gornova/MarteEngine#107]
Hi I just switched from marte engine 0.2 to 0.3 and I got these errors when I try to run my game (Its just experimental project for learning and half of the names are in my first language, which is obviously not English, sorry for that)

> Thu Nov 10 19:15:23 CET 2016 ERROR:Uncompilable source code - incompatible types: it.marteEngine.World cannot be converted to core.states.Hra
java.lang.RuntimeException: Uncompilable source code - incompatible types: it.marteEngine.World cannot be converted to core.states.Hra
	at core.objekty.Pozadi.update(Pozadi.java:32)
	at it.marteEngine.World.update(World.java:175)
	at core.states.Intro.update(Intro.java:32)
	at org.newdawn.slick.state.StateBasedGame.update(StateBasedGame.java:266)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:663)
	at org.newdawn.slick.AppGameContainer.gameLoop(AppGameContainer.java:411)
	at org.newdawn.slick.AppGameContainer.start(AppGameContainer.java:321)
	at core.StartHry.main(StartHry.java:34)
Thu Nov 10 19:15:24 CET 2016 ERROR:Game.update() failure - check the game code.
org.newdawn.slick.SlickException: Game.update() failure - check the game code.
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:669)
	at org.newdawn.slick.AppGameContainer.gameLoop(AppGameContainer.java:411)
	at org.newdawn.slick.AppGameContainer.start(AppGameContainer.java:321)
	at core.StartHry.main(StartHry.java:34)
> 

```
public class StartHry extends StateBasedGame {

    public StartHry(String name) {
        super(name);
    }
    
    static AppGameContainer app;

    /**
     * @param args the command line arguments
     * @throws org.newdawn.slick.SlickException
     */
    public static void main(String[] args) throws SlickException {
        app = new AppGameContainer(new StartHry("Hra"), 800, 600, false);
        app.setVSync(true);
        app.start();
       
    }

    @Override
    public void initStatesList(GameContainer gc) throws SlickException {
        addState(new Intro(0, gc));
        addState(new Hra(1, gc));
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
}
```

```
public class Intro extends World {

    Pozadi backgrIntra;

    public Intro(int id, GameContainer container) throws SlickException {
        super(id, container);
        backgrIntra = new Pozadi(0, 0, new Image("res/Intro.png"), null, 0.8F);
        add(backgrIntra);

    }

    @Override
    public void update(GameContainer container, StateBasedGame game, int delta) throws SlickException {
        super.update(container, game, delta); //To change body of generated methods, choose Tools | Templates.
        if(container.getInput().isKeyPressed(Input.KEY_RETURN)) {
            game.enterState(1);
        }
    }
    

}
```
```
public class Pozadi extends Entity{
Hrac hrac;
    float paralax;

    public Pozadi(float x, float y, Image image, Hrac hrac, float paralax) {
        super(x, y, image);
        this.hrac = hrac;
        this.paralax = paralax;
    }
    
    @Override
    public void update(GameContainer container, int delta) throws SlickException {
        super.update(container, delta); //To change body of generated methods, choose Tools | Templates.
        if (world instanceof Hra) {
            x+=(hrac.previousx-hrac.x)*paralax;
        }
    
}
}
```

("Pozadi" means "Background")
and I got 2 more classes in the project - Hra (that means "game") and Hrac (that means "player")

**Comment by albertotn** [comment]
First thanks for using MarteEngine !!

I strongly suggest you to try and use maven branch, because is most updated one: https://github.com/Gornova/MarteEngine/tree/maven

Evaluating the error, for me it's harder to understand because you don't provide Hra class: could you please provide a minimum example with all involved classes ?

**Comment by jimmyl0l3c** [comment]
Well I haven't changed the code at all, but after reboot of OS it works.
Sorry for my late answer though.

**Comment by albertotn** [comment]
you are welcome!
