### ISSUE TITLE
Tween example isn't working

### ISSUE THREAD

**Issue by Maggistrator** [Gornova/MarteEngine#109]
It's not a big deal, but it would be handy to have actual documentation =)
p.s. to be honest, I'm still don't completely understand how tweens works..

**Comment by Gornova** [comment]
Hi!
Well, there is a [wiki ](https://github.com/Gornova/MarteEngine/wiki)you can use as reference, an [example ](https://github.com/Gornova/MarteEngine/tree/master/test/it/marteEngine/game/starcleaner)to play with it.

On my blog over the years I've written a log about [MarteEngine](https://randomtower.blogspot.com/search/label/marte%20engine) and write down a [Roguelike tutorial](https://randomtower.blogspot.com/p/roguelike-tutorial.html)

If you want to contribute, you are welcome!

About tweens: there is a test [here](https://github.com/Gornova/MarteEngine/tree/master/test/it/marteEngine/test/tween) and how they works, I don't understand in general or here on MarteEngine ?

**Comment by Maggistrator** [comment]
In Marte Engine) 
But tests and your blog make many things clearer - actually, I don't need to use Tweener and Tween classes explicitly, wow o.O
Thanks!
p.s. I've forked ME, and was playing with polygonal collision detection for some time, but just to add it is not actually enough - it has to interact with other systems, so I'm sorting out how those work now)

**Comment by Gornova** [comment]
Well If you have any contribution.. feel fre to share with a PR ! 
I will close for now this issue if is okay for you

**Comment by Maggistrator** [comment]
Sure)
