### ISSUE TITLE
Game State change

### ISSUE THREAD

**Issue by Gornova** [Gornova/MarteEngine#39]
currently when we want to change state in a slick StateBasedGame, we do:

```
         game.enterState(GameWorld.ID, new FadeOutTransition(Color.black),
         new FadeInTransition(Color.black));
```

But.. if GameWorld and current world would pass some entities (for example Editor/GameWorld), World.enter update ME.world  current world for quick reference.. for some strange reason you need to set it in onEnter method of both worlds.. strange but we need to investigate

**Comment by Stef569** [comment]
Is this still an issue?
Fuzzy has 3 worlds and changing between them I could see the ME.world var being updated to the current world.
First Menu then Select Level then Game
