### ISSUE TITLE
Roadmap for this project

### ISSUE THREAD

**Issue by Stef569** [Gornova/MarteEngine#71]
I'm just wondering what the intentions with this project are. People are requesting changes and reporting issues...
But who does the processing/integration. With gornova not being around the project is not advancing.

A paper about what it should do and who is the target audience could help.
Thomas Haaks has given me some pointers: It's based on 'gamemaker', it should be easy to use(hence the public vars?) and it started as a fun project grown into something larger.

For me I think this lib has potential because you always need some shared code between games. A camera, entities, animations, resource loading...

After some games each developer has his camera/resource loading code. It would be better if all this code was grouped into marte.

**Comment by Gornova** [comment]
Hi @Stef569 good to see you back here! 👍

**Comment by Stef569** [comment]
Hey @Gornova :)

I just wanted to fix some small things.

Can you setup a project github page for me? https://pages.github.com/
I need to host a DTD file there. To validate the resources xml file (#97)

**Comment by Gornova** [comment]
@Stef569  I've made setup for http://gornova.github.io/MarteEngine/ but no content here right now, think takes from that branch? 

For version 0.3 yeah sure, it's time 👍 

anyway I've worked a little bit on Maven branch https://github.com/Gornova/MarteEngine/tree/maven if you want to take a look there too

**Comment by Stef569** [comment]
Thanks for making the page @Gornova :+1: 

Now only #42 remains, but It's a bit unclear + I don't need a hitbox as polygon in my game. Fuzzy seems to work fine without it? Let's move it to 4.0 =)

Btw about Fuzzy, I really liked to play it. But I had to cheat because 1 star is unreachable. It was on lvl 7 if I remember well. Also the boss level could use some more love, I didn't get it, eventually the gate opened and I won. Maybe the character should be able to fire bullets at the boss?

**Comment by Gornova** [comment]
for fuzzy and other examples, maybe is better to move in another project ? 

for #42 let's close it and forget, for MarteEngine a simple rectangular hitbox is okay, what do you think ?

**Comment by Stef569** [comment]
Hey Gornova
I updated the project to version 0.3
Fuzzy is like a large example it can stay for now :)
Let's do the simple rectangular hitbox :)
Take care!

**Comment by Gornova** [comment]
well done
