### ISSUE TITLE
resource xml validation

### ISSUE THREAD

**Issue by demoth** [Gornova/MarteEngine#97]
not sure if it was already discussed (haven't found it in closed and opened issues) but since we use xml for loading resources (XMLResoucreLoader) it is possible to use xml validation instead of checking the root element

**Comment by Stef569** [comment]
The DTD can be found here:
http://gornova.github.io/MarteEngine/0.3/resourceManager.dtd

Add
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE resources SYSTEM "http://gornova.github.io/MarteEngine/0.3/resourceManager.dtd">

above the XML file to validate the content :)
